TRAIN_ANN_FILE = "./dataset/annotations_trainval2017/annotations/instances_train2017.json"
VAL_ANN_FILE = "./dataset/annotations_trainval2017/annotations/instances_val2017.json"
IMG_SIZE = (224,224)
GRID_SIZE = 7
BATCH_SIZE = 128
NUM_CLASSES = 80
ANNOTATIONS_REQUIRED = [
        "bbox",
        "category_id",
        "image_id"
        ]


COCO_CLASSES_ES = {
        1: 'persona', 
        2: 'bicicleta', 
        3: 'coche / auto', 
        4: 'motocicleta', 
        5: 'avión', 
        6: 'autobús', 
        7: 'tren', 
        8: 'camión', 
        9: 'bote', 
        10: 'semáforo', 
        11: 'boca de incendios', 
        12: 'señal de stop',
        13: 'parquímetro', 
        14: 'banco', 
        15: 'pájaro', 
        16: 'gato', 
        17: 'perro', 
        18: 'caballo', 
        19: 'oveja', 
        20: 'vaca', 
        21: 'elefante', 
        22: 'oso', 
        23: 'cebra', 
        24: 'jirafa', 
        25: 'mochila', 
        26: 'paraguas', 
        27: 'bolso', 
        28: 'corbata', 
        29: 'maleta', 
        30: 'frisbee', 
        31: 'esquís', 
        32: 'snowboard',
        33: 'balón deportivo', 
        34: 'cometa', 
        35: 'bate de béisbol', 
        36: 'guante de béisbol', 
        37: 'monopatín', 
        38: 'tabla de surf', 
        39: 'raqueta de tenis',
        40: 'botella', 
        41: 'copa de vino', 
        42: 'taza', 
        43: 'tenedor', 
        44: 'cuchillo', 
        45: 'cuchara', 
        46: 'cuenco', 
        47: 'plátano / banana', 
        48: 'manzana', 
        49: 'sándwich', 
        50: 'naranja',
        51: 'brócoli', 
        52: 'zanahoria', 
        53: 'perrito caliente', 
        54: 'pizza', 
        55: 'dona', 
        56: 'pastel', 
        57: 'silla', 
        58: 'sofá', 
        59: 'planta en maceta', 
        60: 'cama', 
        61: 'mesa de comedor', 
        62: 'inodoro', 
        63: 'televisión', 
        64: 'portátil', 
        65: 'ratón', 
        66: 'control remoto', 
        67: 'teclado', 
        68: 'teléfono móvil', 
        69: 'microondas', 
        70: 'horno', 
        71: 'tostadora', 
        72: 'fregadero', 
        73: 'refrigerador', 
        74: 'libro', 
        75: 'reloj', 
        76: 'jarrón', 
        77: 'tijeras', 
        78: 'oso de peluche', 
        79: 'secador de pelo', 
        80: 'cepillo de dientes'}



