TRAIN_ANN_FILE = "./dataset/annotations_trainval2017/annotations/instances_train2017.json"
VAL_ANN_FILE = "./dataset/annotations_trainval2017/annotations/instances_val2017.json"
ANNOTATIONS_REQUIRED = [
        "bbox",
        "category_id",
        "image_id"
        ]


COCO_CLASSES_ES = {
    1: "persona",
    2: "bicicleta",
    3: "coche / auto",
    4: "motocicleta",
    5: "avión",
    6: "autobús",
    7: "tren",
    8: "camión",
    9: "bote",
    10: "semáforo",
    11: "boca de incendios",
    13: "señal de stop",
    14: "parquímetro",
    15: "banco",
    16: "pájaro",
    17: "gato",
    18: "perro",
    19: "caballo",
    20: "oveja",
    21: "vaca",
    22: "elefante",
    23: "oso",
    24: "cebra",
    25: "jirafa",
    27: "mochila",
    28: "paraguas",
    31: "bolso",
    32: "corbata",
    33: "maleta",
    34: "frisbee",
    35: "esquís",
    36: "snowboard",
    37: "balón deportivo",
    38: "cometa",
    39: "bate de béisbol",
    40: "guante de béisbol",
    41: "monopatín",
    42: "tabla de surf",
    43: "raqueta de tenis",
    44: "botella",
    46: "copa de vino",
    47: "taza",
    48: "tenedor",
    49: "cuchillo",
    50: "cuchara",
    51: "cuenco",
    52: "plátano / banana",
    53: "manzana",
    54: "sándwich",
    55: "naranja",
    56: "brócoli",
    57: "zanahoria",
    58: "perrito caliente",
    59: "pizza",
    60: "dona",
    61: "pastel",
    62: "silla",
    63: "sofá",
    64: "planta en maceta",
    65: "cama",
    67: "mesa de comedor",
    70: "inodoro",
    72: "televisión",
    73: "portátil",
    74: "ratón",
    75: "control remoto",
    76: "teclado",
    77: "teléfono móvil",
    78: "microondas",
    79: "horno",
    80: "tostadora",
    81: "fregadero",
    82: "refrigerador",
    84: "libro",
    85: "reloj",
    86: "jarrón",
    87: "tijeras",
    88: "oso de peluche",
    89: "secador de pelo",
    90: "cepillo de dientes"
}
